project:
  type: website
  output-dir: docs

website:
  title: "CATS"
  site-url: "http://kbodwin.github.io/CATS"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

resources:
  - "images/*"

